version: '2'

services:

  couchclient:
      image: 192.168.1.151:32000/couchclient:1.0.114
      build:
          context: ./
          dockerfile: ./Dockerfile
      restart: unless-stopped
      ports:
          - "5001:443"
