version: '2'

services:

  couchclient:
      image: neon-registry.4e88-13d3-b83a-9fc9.neoncluster.io/leenet/couchclient:1.0.131
      build:
          context: ./
          dockerfile: ./Dockerfile
      restart: unless-stopped
      ports:
          - "5001:443"
